const http=require("http"),fs=require("fs"),path=require("path"),crypto=require("crypto");
const port=process.env.PORT||3000;
const adminUser=process.env.ADMIN_USER||"admin", adminPass=process.env.ADMIN_PASSWORD||"change-me";
const staffUser=process.env.STAFF_USER||"", staffPass=process.env.STAFF_PASSWORD||"";
const html=fs.readFileSync(path.join(__dirname,"index.html"),"utf8");
const sessions=new Map();
function setCookie(res,token){res.setHeader("Set-Cookie",`bh_session=${token}; HttpOnly; Path=/; SameSite=Lax; Max-Age=604800`)}
function clearCookie(res){res.setHeader("Set-Cookie","bh_session=; HttpOnly; Path=/; SameSite=Lax; Max-Age=0")}
function sessionRole(req){const m=(req.headers.cookie||"").match(/(?:^|; )bh_session=([^;]+)/);return m?sessions.get(m[1]):null}
function loginPage(message=""){
return `<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="default"><meta name="apple-mobile-web-app-title" content="BestellungBH"><meta name="theme-color" content="#0b6f70"><link rel="apple-touch-icon" sizes="180x180" href="https://static.wixstatic.com/media/4dabb2_6a7f5cbdb5fb4c51b0830e92895aa09b~mv2.png/v1/fill/w_254,h_182,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/4dabb2_6a7f5cbdb5fb4c51b0830e92895aa09b~mv2.png"><title>BestellungBH – Anmeldung</title><style>*{box-sizing:border-box}body{margin:0;min-height:100vh;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#f5f6f7;color:#172126;display:flex;align-items:center;justify-content:center;padding:24px}.login{width:min(420px,100%);background:#fff;border:1px solid #dfe5e7;border-radius:22px;padding:28px 22px;box-shadow:0 10px 30px #00000010;text-align:center}.logo{width:150px;height:108px;object-fit:contain;margin:4px auto 10px;display:block}.title{font-size:25px;font-weight:700}.sub{color:#66737a;margin:6px 0 24px}.field{text-align:left;margin:12px 0}.field label{display:block;font-size:13px;color:#66737a;margin-bottom:6px}.field input{width:100%;font:inherit;font-size:17px;padding:13px;border:1px solid #dfe5e7;border-radius:12px;outline:none}.field input:focus{border-color:#0b6f70;box-shadow:0 0 0 3px #0b6f7020}.submit{width:100%;border:0;border-radius:12px;background:#0b6f70;color:#fff;font:inherit;font-weight:650;font-size:17px;padding:14px;margin-top:8px}.error{background:#fff1f0;border:1px solid #f2c5c1;color:#9f1c13;border-radius:10px;padding:10px;margin:12px 0;text-align:left}</style></head><body><form class="login" method="post" action="/login"><img class="logo" src="https://static.wixstatic.com/media/4dabb2_6a7f5cbdb5fb4c51b0830e92895aa09b~mv2.png"><div class="title">BestellungBH</div><div class="sub">Beach House · Bestellungssystem</div>${message?`<div class="error">${message}</div>`:""}<div class="field"><label>Benutzername</label><input name="username" autocomplete="username" required></div><div class="field"><label>Passwort</label><input name="password" type="password" autocomplete="current-password" required></div><button class="submit" type="submit">Anmelden</button></form></body></html>`;
}
function serveApp(res,role){const body=html.replace("const CURRENT_ROLE='__ROLE__';",`const CURRENT_ROLE='${role}';`);res.writeHead(200,{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-store"});res.end(body)}
function readBody(req){return new Promise((resolve,reject)=>{let b="";req.on("data",c=>{b+=c;if(b.length>10000)req.destroy()});req.on("end",()=>resolve(new URLSearchParams(b)));req.on("error",reject)})}
const server=http.createServer(async(req,res)=>{try{
if(req.url==="/health"){res.writeHead(200,{"Content-Type":"text/plain"});res.end("ok");return}
if(req.url==="/logout"&&(req.method==="POST"||req.method==="GET")){const m=(req.headers.cookie||"").match(/(?:^|; )bh_session=([^;]+)/);if(m)sessions.delete(m[1]);clearCookie(res);res.writeHead(req.method==="GET"?303:204,req.method==="GET"?{Location:"/"}:undefined);res.end();return}
if(req.url==="/login"&&req.method==="POST"){const f=await readBody(req),u=f.get("username")||"",p=f.get("password")||"";let role=null;if(u===adminUser&&p===adminPass)role="admin";else if(staffUser&&staffPass&&u===staffUser&&p===staffPass)role="staff";if(!role){res.writeHead(401,{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-store"});res.end(loginPage("Benutzername oder Passwort ist nicht korrekt."));return}const token=crypto.randomBytes(32).toString("hex");sessions.set(token,role);setCookie(res,token);res.writeHead(303,{Location:"/"});res.end();return}
if(req.url==="/"||req.url.startsWith("/index.html")){const role=sessionRole(req);if(!role){res.writeHead(200,{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-store"});res.end(loginPage());return}serveApp(res,role);return}
res.writeHead(404);res.end("Not found");
}catch(e){console.error(e);res.writeHead(500);res.end("Server error")}});
server.listen(port,"0.0.0.0",()=>console.log("BestellungBH listening on "+port));
